### ISSUE TITLE
Several function names conflict with TurboGML

### ISSUE THREAD

**Issue by Slackaduts** [FoxyOfJungle/Burrn#1]
Some function names of this library conflict with those used in [TurboGML](https://github.com/FoxyOfJungle/TurboGML):
- [particle_move()](https://github.com/FoxyOfJungle/Burrn/blob/2c98bf113f33b969da9fe37c5b851c4a240fd28e/scripts/__bpe_particles/__bpe_particles.gml#LL46C44-L46C44)
- [particle_set_emission_enabled()](https://github.com/FoxyOfJungle/Burrn/blob/2c98bf113f33b969da9fe37c5b851c4a240fd28e/scripts/__bpe_particles/__bpe_particles.gml#LL85C63-L85C63)
- [particle_set_emission()](https://github.com/FoxyOfJungle/Burrn/blob/2c98bf113f33b969da9fe37c5b851c4a240fd28e/scripts/__bpe_particles/__bpe_particles.gml#L100)
- [particle_pause()](https://github.com/FoxyOfJungle/Burrn/blob/2c98bf113f33b969da9fe37c5b851c4a240fd28e/scripts/__bpe_particles/__bpe_particles.gml#L106)

**Comment by FoxyOfJungle** [comment]
Hello,

These functions have been moved to the Burrn library repository. Soon they
will no longer be in TurboGML.
Thanks for letting me know!

Cheers!

Em sáb., 10 de jun. de 2023 às 15:08, Slackaduts ***@***.***>
escreveu:
